Digital Library - Avocada
Technigo/project-library pull request #34
Opened 2024-02-25 18:52 UTC by pernillasterner

## Netlify link
[View it live](https://technigo-project-library.netlify.app/)

## Collaborators
No collaborators this week

2024-02-28 10:41 UTC, fridaforser commented on js/main.js
> +// Load the initial list of dogs when the page loads
Just a little error I found, it says "dogs" instead of recipes :)

2024-02-28 10:47 UTC, fridaforser commented
Hi,

Good job this week! You can definitely tell you are comfortable with writing a lot of code, so much that a newbie like myself had some trouble understanding some parts, but it was easy to follow the comments and the flow, and I trust that you tweaked the code and kept it as dry as you could. 

I however noticed that the sorting didn't really work, however I personally loved the checkboxes in the filtering section, so the user can make multiple choices - well done!

Overall, you did a great job and I really like the vibe of your library, I just wish I was able to understand more of the code and how it all works together, but that's on me for not having that much previous coding experience.

I only added one small comment with a little error I found :)

2024-02-28 15:33 UTC, AntonellaMorittu requested changes
Hi Pernilla, well done finishing your Library app 📚 You are an high-achiever, your app looks fabulous and I appreciate the effort in trying to have a modular approach with this project. However, the filtering and sorting features are buggy and the behaviour doesn't work as expected. I strongly recommend to use a single script file and have all your functions there. Fix the buggy filters and sorting functionality and you're good to go :)

2024-02-28 15:33 UTC, AntonellaMorittu commented on .DS_Store
Please add .DS_Store to your .gitignore file (if you don't have one, you need to create it) and remove the file from the repo 👍

2024-02-28 15:33 UTC, AntonellaMorittu commented on assets/.DS_Store
same here 🧹

2024-03-01 07:07 UTC, pernillasterner commented on .DS_Store
Hi Antonella, the .DS_Store is already in my .gitignore file but perhaps I created it the initial commit. Thanks for letting me know :)

2024-03-01 07:12 UTC, pernillasterner commented
@AntonellaMorittu @fridaforser 
Can you give me some more details about what is not working with the filter and sorting functionality so I have something to go on? :)
The filter dropdown works as long as you click on either clear all or close. Can´t find the bug when it comes to the sorting.

2024-03-05 13:09 UTC, AntonellaMorittu approved these changes

2024-03-05 13:09 UTC, NellaMori approved these changes

2024-09-17 08:25 UTC, closed without merging